apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker:
      buildArgs:
        version: '{{.VERSION}}'
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/colmmurphy91/core-team-service:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/colmmurphy91/core-team-service:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: core-team-service
        chartPath: charts/core-team-service
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/colmmurphy91/core-team-service'
          image.tag: '{{.DIGEST_HEX}}'
