eureka:
  client:
    enabled: false

spring:
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@clubmanagementsystem-liwrx.gcp.mongodb.net/staging?retryWrites=true
      authentication-database: admin
  application:
    name: core-team-service

server:
  port: 8080

